export const SET_CURRENT_QUESTION = 'SET_CURRENT_QUESTION';
export const SET_ANSWERS = 'SET_ANSWERS';
export const SET_TOTAL_QUESTIONS = 'SET_TOTAL_QUESTIONS';
export const SET_ALL_QUESTIONS = 'SET_ALL_QUESTIONS';
export const SET_ALL_ANSWERS_NULL = 'SET_ALL_ANSWERS_NULL';
export const SET_RESET_QUIZ = 'SET_RESET_QUIZ';
